### PR TITLE
Refactored Args to use AsRef<Path> instead of Path to resolve #4

### LINKED ISSUE #4: Improve ergonomics when dealing with `glob`s.
Would it be possible to change  `flatc_rust::Args.inputs` to accept things of type `AsRef<Path>` instead of regular `Path`?  That way it could accept `PathBuf`s as well, which would make it easier to get it to interact with the `glob` crate.

Would it be easy enough that a intermediate Rustacean might be able to send you a PR?

### PR DESCRIPTION
**Pull request by dunmatt**
This is an alternate approach that doesn't change the API under normal use cases (ie those where there are inputs).  Is this better?

### CODE REVIEW

**Comment by frol** [comment]
What is your use-case, by the way? Would it be easier to just wrap the existing API on your way?

**Comment by dunmatt** [comment]
The use case seems like a pretty obvious one, I want to compile all the flatbuffers in a given directory, so I'm using `glob` to iterate over the files.  The trouble is, `glob` returns `PathBuf`s instead of `Path`s.  I'm not sure I follow what you mean by "on my way"

**Comment by frol** [comment]
Oh, I meant "on your side".

I want to let you know that I will be able to review, merge and release a new version of the crate only on Monday as I am hiking :)

I want to see if there is a better way to work with `PathBuf` as I don't really like the hack around `Default` implementation.

**Comment by dunmatt** [comment]
For sure, it can easily be solved on my side, it just seemed like an obvious and common pain point so I figured I'd offer it upstream.  For those curious for an easy local solution:

```rust
let flatbuffers: Vec<_> =
    glob("msg/**/*.fbs").expect("Error globbing for flatbuffer specs.").flatten().collect();
let flatbuffers: Vec<_> = flatbuffers.iter().map(|p| p.as_path()).collect();

flatc_rust::run(flatc_rust::Args {
    inputs: &flatbuffers,
    out_dir: Path::new("target/flatbuffers/"),
    ..Default::default()
})
.expect("flatc");
```

**Comment by frol** [comment]
@dunmatt Having tried your PRs and a few other ideas I ended up with a conclusion that my configuration strategy is quite limiting and should be redesigned from scratch. Also, I believe not all of the API shortcomings have shown themselves yet, so I would like to let it be as it is now [without breaking API changes] and wait for other reasons to break the API.

Thank you for your contribution!

**Pull request closed without merging**
